"""Tool to format the final structured LeetCode learning guide."""


def format_learning_plan(
    topic: str,
    problems: str = "",
    tutorials: str = "",
    schedule: str = "",
) -> str:
    """Format a complete LeetCode learning guide from individual sections.

    Assembles the problem list, tutorial summaries, and practice schedule
    into a clean, well-structured markdown learning guide.

    Args:
        topic: The DSA topic name.
        problems: Formatted string of recommended problems.
        tutorials: Formatted string of tutorial summaries.
        schedule: Formatted string of the practice schedule.

    Returns:
        A formatted markdown string containing the full learning plan.
    """
    sections = []

    sections.append(f"# 📘 LeetCode Learning Guide: {topic}\n")

    if problems:
        sections.append("## 🔗 Recommended Problems\n")
        sections.append(problems)
        sections.append("")

    if tutorials:
        sections.append("## 📚 Tutorial Summaries\n")
        sections.append(tutorials)
        sections.append("")

    if schedule:
        sections.append("## 📅 7-Day Practice Schedule\n")
        sections.append(schedule)
        sections.append("")

    sections.append("## 💡 Tips for Success\n")
    sections.append(
        "- **Consistency beats intensity** — practice daily, even if only for 30 minutes.\n"
        "- **Understand, don't memorize** — focus on *why* a solution works.\n"
        "- **Use the discussion tab** — learn from other approaches after solving.\n"
        "- **Track your progress** — keep a log of solved problems and revisit weak areas.\n"
    )

    sections.append("---\n*Generated by LeetCode Learning Assistant*")

    return "\n".join(sections)